site_name: My Docs
repo_url: https://afritzler.github.io/mydocs-action-test/
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true